spack:
  specs:
  - cosmo-eccodes-definitions@2.25.0.1
  - icon @develop %nvhpc +grib2 +eccodes-definitions +ecrad +emvorado +art +dace gpu=openacc+cuda +mpi-gpu +realloc-buf ~aes ~jsbach ~ocean ~coupling ~rte-rrtmgp ~loop-exchange ~async-io-rma
  view: true
  concretizer:
    unify: true
  develop:
    icon:
      path: ../../../../..
      spec: icon @develop %nvhpc +grib2 +eccodes-definitions +ecrad +emvorado +art +dace gpu=openacc+cuda +mpi-gpu +realloc-buf ~aes ~jsbach ~ocean ~coupling ~rte-rrtmgp ~loop-exchange ~async-io-rma
