spack:
  specs:
  - cosmo-eccodes-definitions@2.25.0.1
  - icon @develop %nvhpc +eccodes-definitions +ecrad ~jsbach ~loop-exchange +mixed-precision ~ocean +rte-rrtmgp
  view: true
  concretizer:
    unify: true
  develop:
    icon:
      path: ../../../../..
      spec: icon @develop %nvhpc +eccodes-definitions +ecrad ~jsbach ~loop-exchange +mixed-precision ~ocean +rte-rrtmgp
