# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs:
  - icon@develop%nvhpc +ecrad +rte-rrtmgp +art gpu=60 +mixed-precision +dace fcgroup=DACE;externals/dace_icon;-O1
  - eccodes@2.19.0%nvhpc
  - nvidia-blas%nvhpc
  - nvidia-lapack%nvhpc
  - libxml2@2.9.13%gcc
  view: false
  concretizer:
    unify: true
  develop:
    icon:
      spec: icon@develop%nvhpc +ecrad +rte-rrtmgp +art gpu=60 +mixed-precision +dace fcgroup=DACE;externals/dace_icon;-O1
      path: ../../../../../
