#!/bin/bash

SPACK_REMOTE='https://github.com/C2SM/spack-c2sm.git'
SPACK_COMMIT=mch_env_3

SPACK_SPEC="icon@cpu%nvhpc icon_target=cpu +eccodes ^eccodes@2.19.1"
 

git clone ${SPACK_REMOTE}

pushd spack-c2sm
git checkout $SPACK_COMMIT
git submodule init
git submodule update
. setup-env.sh
popd

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

spack dev-build -u build ${SPACK_SPEC}
