#!/bin/bash

set -e

# set required environment variables
export MODULESHOME="/usr/share/Modules"

# this wrapper needs to build two ICON binaries
MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

# =============================================================================
# create vector engine binary

mkdir -p build/vector
cd build/vector

${ICON_DIR}/config/dwd/rcl.VE.bb-dwd_nec_yac2 --prefix=${ICON_DIR}/vector


if test 0 -ne "$?" && test ! -z "${BB_NAME}"; then
  echo " ***** Configuration logs from '$(pwd)' ***** "
  for f in $(find . -name 'config.log' -print); do
    echo " ||||| '$f' ||||| "
    cat "$f"
  done
  echo " ***** End of configuration logs from '$(pwd)' ***** "
fi

MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install

cd ../../

# copy a valid info file to where runexp expects it. buildbot is doing
# in-source-builds, only at the moment
cp -v $OLDPWD/run/set-up.info run/

# =============================================================================
# create vector host binary
mkdir -p build/host
cd build/host
${ICON_DIR}/config/dwd/rcl.VH.bb-dwd_nec_yac2 --prefix=${ICON_DIR}/host

if test 0 -ne "$?" && test ! -z "${BB_NAME}"; then
  echo " ***** Configuration logs from '$(pwd)' ***** "
  for f in $(find . -name 'config.log' -print); do
    echo " ||||| '$f' ||||| "
    cat "$f"
  done
  echo " ***** End of configuration logs from '$(pwd)' ***** "
fi

MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install

cd ../..

# =============================================================================
VECTOR_BINARY=${ICON_DIR}/vector/bin/icon
HOST_BINARY=${ICON_DIR}/host/bin/icon

set +e
find "${PWD}/vector" "${PWD}/host"
file "$VECTOR_BINARY" "$HOST_BINARY"
