#!/bin/bash

set -e

# set required environment variables
export MODULESHOME="/usr/share/Modules"

# this wrapper needs to build two ICON binaries
MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

# these setting are critical to proper logging by buildbot
export VE_DIR="${ICON_DIR}/build/vector"
export VH_DIR="${ICON_DIR}/build/host"

# =============================================================================
# create vector engine binary

mkdir -p ${VE_DIR}
cd ${VE_DIR}

${ICON_DIR}/config/dwd/rcl.VE.bb-dwd_nec_yac2 --prefix=${ICON_DIR}/vector


if test 0 -ne "$?" && test ! -z "${BB_NAME}"; then
  echo " ***** Configuration logs from '$(pwd)' ***** "
  for f in $(find . -name 'config.log' -print); do
    echo " ||||| '$f' ||||| "
    cat "$f"
  done
  echo " ***** End of configuration logs from '$(pwd)' ***** "
fi

MAKE_PROCS=14
make -j ${MAKE_PROCS} |& tee make.log
make install

cd -

# copy a valid info file to where runexp expects it. buildbot is doing
# in-source-builds, only at the moment
cp -v $OLDPWD/run/set-up.info run/

# =============================================================================
# create vector host binary
mkdir -p ${VH_DIR}
cd ${VH_DIR}
${ICON_DIR}/config/dwd/rcl.VH.bb-dwd_nec_yac2 --prefix=${ICON_DIR}/host

if test 0 -ne "$?" && test ! -z "${BB_NAME}"; then
  echo " ***** Configuration logs from '$(pwd)' ***** "
  for f in $(find . -name 'config.log' -print); do
    echo " ||||| '$f' ||||| "
    cat "$f"
  done
  echo " ***** End of configuration logs from '$(pwd)' ***** "
fi

MAKE_PROCS=14
make -j ${MAKE_PROCS} |& tee make.log
make install

cd -

# =============================================================================
VECTOR_BINARY=${ICON_DIR}/vector/bin/icon
HOST_BINARY=${ICON_DIR}/host/bin/icon

set +e
find "${ICON_DIR}/vector" "${ICON_DIR}/host"
file "$VECTOR_BINARY" "$HOST_BINARY"
