#!/bin/bash

set -e

# set required environment variables
export MODULESHOME="/usr/share/Modules"

# this wrapper needs to build two ICON binaries
MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

# create vector engine binary
#${ICON_DIR}/config/dwd/rcl.VE.nfort --enable-openmp --prefix=${PWD}/vector
${ICON_DIR}/config/dwd/rcl.VE.nfort-3.5.1_mpi-2.20_art_oper --prefix=${PWD}/vector
MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install


# Save the _vector_ info file as it is required for
# create_target_header afterwards.
mv -v run/set-up.info run/set-up.info.vector

make distclean

# create vector host binary
#${ICON_DIR}/config/dwd/rcl.VH.gcc --prefix=${PWD}/host
${ICON_DIR}/config/dwd/rcl.VH.gcc-9.1.0_mpi-2.20_art_oper --prefix=${PWD}/host
MAKE_PROCS=14
make -j ${MAKE_PROCS}
make install

VECTOR_BINARY="${PWD}/vector/bin/icon"
HOST_BINARY="${PWD}/host/bin/icon"

set +e
find "${PWD}/vector" "${PWD}/host"
file "$VECTOR_BINARY" "$HOST_BINARY"

# Restore the _vector_ info file as it is required for create_target_header.
mv -v run/set-up.info.vector run/set-up.info
# Copy the vector binary to the place, that is stored as builddir in set-up.info.
# Only then it can be found by create_target_header.
cp "${VECTOR_BINARY}" "${PWD}/bin/icon"
