#!/bin/bash
set -eu

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

if [ ! -z "${BB_NAME-}" ]; then
  MAKE_PROCS=22
else
  MAKE_PROCS=8
fi

${ICON_DIR}/config/kit/hk.cpu.gcc
make -j ${MAKE_PROCS}

if [ ! -z "${BB_NAME-}" ] ; then
  "${ICON_DIR}/scripts/buildbot_scripts/build_checks/check_depgen_warnings.sh"
  "${ICON_DIR}/scripts/buildbot_scripts/build_checks/check_remake.sh"
  "${ICON_DIR}/scripts/buildbot_scripts/build_checks/check_git_untracked.sh"
fi
