#!/bin/bash

set -e

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

MAKE_PROCS=8

# Change to new build wrappers as soon as they are included and eurohack wrappers are removed
nvhpc_wrapper_set=0


# Go one step up - otherwise the there might be recursive calls in "make install"
cd ${ICON_DIR}


# =============================================================================
# Build CPU binary

mkdir -p build/cpurun
cd build/cpurun
if [ ${nvhpc_wrapper_set} -eq 0 ]; then
   ${ICON_DIR}/config/dkrz/levante.cpu.nvhpc-22.5_eurohack --prefix=${ICON_DIR}/cpurun
else
   ${ICON_DIR}/config/dkrz/levante.cpu.nvhpc-22.5 --prefix=${ICON_DIR}/cpurun \
   'FCFLAGS=-I/sw/spack-levante/netcdf-fortran-4.5.4-syv4qr/include -g -O2 -Mrecursive -Mallocatable=03 -Mstack_arrays -Minfo=inline -Mnofma '
fi

make -j ${MAKE_PROCS}
cd ../../


# =============================================================================
# Build GPU binary

mkdir -p build/gpurun
cd build/gpurun
if [ ${nvhpc_wrapper_set} -eq 0 ]; then
   ${ICON_DIR}/config/dkrz/levante.gpu.nvhpc-22.5_eurohack --prefix=${ICON_DIR}/gpurun
else
   ${ICON_DIR}/config/dkrz/levante.gpu.nvhpc-22.5 --prefix=${ICON_DIR}/gpurun \
   'FCFLAGS=-I/sw/spack-levante/netcdf-fortran-4.5.4-syv4qr/include -g -O2 -Mrecursive -Mallocatable=03 -Mstack_arrays -Minfo=accel,inline -acc=gpu,verystrict -gpu=cc80,math_uniform -Mnofma '
fi

make -j ${MAKE_PROCS}
cd ../../


# =============================================================================
# Build CPU LVECTOR binary

mkdir -p build/cpurun_lvec
cd build/cpurun_lvec
if [ ${nvhpc_wrapper_set} -eq 0 ]; then
   ${ICON_DIR}/config/dkrz/levante.cpu.nvhpc-22.5_eurohack --prefix=${ICON_DIR}/cpurun_lvec \
   'FCFLAGS=-g -I/sw/spack-levante/netcdf-fortran-4.5.3-ojzrgm/include -L/sw/spack-levante/gcc-11.2.0-bcn7mb/lib64 -lstdc++ -Mallocatable=03 -D__SWAPDIM -O2 -Mnofma -D__LVECTOR__ -D__LVEC_BITID__ '
else
   ${ICON_DIR}/config/dkrz/levante.cpu.nvhpc-22.5 --prefix=${ICON_DIR}/cpurun_lvec \
   'FCFLAGS=-I/sw/spack-levante/netcdf-fortran-4.5.4-syv4qr/include -g -O2 -Mrecursive -Mallocatable=03 -Mstack_arrays -Minfo=inline -Mnofma -D__LVECTOR__ -D__LVEC_BITID__ '
fi

make -j ${MAKE_PROCS}
cd ../../


# =============================================================================
# Build GPU LVECTOR binary

mkdir -p build/gpurun_lvec
cd build/gpurun_lvec
if [ ${nvhpc_wrapper_set} -eq 0 ]; then
   ${ICON_DIR}/config/dkrz/levante.gpu.nvhpc-22.5_eurohack --prefix=${ICON_DIR}/gpurun_lvec \
   'FCFLAGS=-g -I/sw/spack-levante/netcdf-fortran-4.5.3-ojzrgm/include -L/sw/spack-levante/gcc-11.2.0-bcn7mb/lib64 -lstdc++ -Mallocatable=03 -acc=verystrict -Minfo=accel,inline -gpu=cc80,math_uniform,cuda11.7 -D__SWAPDIM -D__USE_G2G -O2 -Mnofma -D__LVECTOR__ -D__LVEC_BITID__ '
else
   ${ICON_DIR}/config/dkrz/levante.gpu.nvhpc-22.5 --prefix=${ICON_DIR}/gpurun_lvec \
   'FCFLAGS=-I/sw/spack-levante/netcdf-fortran-4.5.4-syv4qr/include -g -O2 -Mrecursive -Mallocatable=03 -Mstack_arrays -Minfo=accel,inline -acc=gpu,verystrict -gpu=cc80,math_uniform -Mnofma -D__LVECTOR__ -D__LVEC_BITID__ '
fi

make -j ${MAKE_PROCS}
cd ../../


# =============================================================================
# Copy set-up.info file to the base run directory in ${ICON_DIR} where runexp expects it
cp -v build/gpurun/run/set-up.info run/


# =============================================================================
# Check successfull creation and installation

set +e
file "${ICON_DIR}/build/cpurun/bin/icon" "${ICON_DIR}/build/gpurun/bin/icon" "${ICON_DIR}/build/cpurun_lvec/bin/icon" "${ICON_DIR}/build/gpurun_lvec/bin/icon"
