#!/bin/bash

set -eu

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

if [ ! -z "${BB_NAME-}" ] ; then
  MAKE_PROCS=22
else
  MAKE_PROCS=8
fi

${ICON_DIR}/config/csc/lumi.container_wrapper.cce bash -i - <<EOF
set -eu
${ICON_DIR}/config/csc/lumi.cpu.cce
make -j ${MAKE_PROCS} V=1
EOF
