#!/bin/bash

set +x

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)


if [ ! -z "${BB_NAME}" ] ; then
  MPI_LAUNCH='srun -A mh0156 -p compute,compute2 -N 1'
else
  MPI_LAUNCH=''
fi


${ICON_DIR}/config/dkrz/mistral.gcc --enable-yaxt --disable-openmp MPI_LAUNCH="${MPI_LAUNCH}"

if test 0 -ne "$?" ; then
  find . -name 'config.log' -print | xargs -I {} sh -c "echo '#====== FILE:{} =======================================' && cat {}"
  exit 1
fi

if [ ! -z "${BB_NAME}" ] ; then
  MAKE_PROCS=22
  echo "MAKE_PROCS=${MAKE_PROCS}"
else
  MAKE_PROCS=8
fi
make -j ${MAKE_PROCS} || exit 1
