#!/bin/bash

MY_DIR=$(cd "$(dirname "$0")"; pwd)
ICON_DIR=$(cd "${MY_DIR}/../.."; pwd)

${ICON_DIR}/config/dkrz/mistral.intel-17.0.6 --enable-yaxt --enable-openmp

if [ ! -z "${BB_NAME}" ] ; then
  MAKE_PROCS=22
  echo "MAKE_PROCS=${MAKE_PROCS}"
else
  MAKE_PROCS=8
fi
make -j ${MAKE_PROCS}
