spack:
  specs:
  - cosmo-eccodes-definitions@2.25.0.1
  - icon @develop %nvhpc +eccodes-definitions +ecrad gpu=80 ~jsbach ~loop-exchange ~ocean +rte-rrtmgp ~async-io-rma
  view: true
  concretizer:
    unify: true
  develop:
    icon:
      path: ../../../../..
      spec: icon @develop %nvhpc +eccodes-definitions +ecrad gpu=80 ~jsbach ~loop-exchange ~ocean +rte-rrtmgp ~async-io-rma
