#!/bin/bash

addexp="./addexp"
#############################################################################
listname=debug2
./rmlist $listname

./create_all_builders $listname

# deactivate all builders
./set_builder_flags Inactive --builders "$(./lslist $listname --builders-only)" --list $listname

#lets see the list
./lslist $listname
#-----------------------------------------------------------

