#!/bin/bash

# abort on error
set -euo pipefail

cd $(dirname "${BASH_SOURCE[0]}")
set -x
addexp="./addexp"
#############################################################################
##
## create ocean list
##
#############################################################################
listname=oes-ref
./rmlist $listname

./create_ocean_builders $listname

#-----------------------------------------------------------
# OES

# add omip binary-identical test on mistral
$addexp checksuite.ocean_internal/omip/exp.test_ocean_omip_10days \
--machines levante --without-configureflags '--enable-mixed' --runflags "cpu_time=00:30:00 queue=compute" --list $listname
$addexp checksuite.ocean_internal/omip/exp.test_ocean_zstar_omip_10days \
--machines levante --without-configureflags '--enable-mixed' --runflags "cpu_time=00:30:00 queue=compute" --list $listname
$addexp checksuite.ocean_internal/hamocc/exp.test_hamocc_omip_10days       \
--machines levante --without-configureflags '--enable-mixed' --runflags "cpu_time=00:30:00 queue=compute" --list $listname

$addexp checksuite.ocean_internal/omip/pp.refgen_test_ocean_omip_10days  --machines levante --without-configureflags '--enable-mixed' --list $listname
$addexp checksuite.ocean_internal/omip/pp.refgen_test_ocean_zstar_omip_10days  --machines levante --without-configureflags '--enable-mixed' --list $listname
$addexp checksuite.ocean_internal/hamocc/pp.refgen_test_hamocc_omip_10days --machines levante --without-configureflags '--enable-mixed' --list $listname



./adddep --from-experiment checksuite.ocean_internal/omip/pp.refgen_test_ocean_omip_10days \
         --to-experiment checksuite.ocean_internal/omip/exp.test_ocean_omip_10days \
	 --machines levante --without-configureflags '--enable-mixed' --list $listname
./adddep --from-experiment checksuite.ocean_internal/omip/pp.refgen_test_ocean_zstar_omip_10days \
         --to-experiment checksuite.ocean_internal/omip/exp.test_ocean_zstar_omip_10days \
	 --machines levante --without-configureflags '--enable-mixed' --list $listname
./adddep --from-experiment checksuite.ocean_internal/hamocc/pp.refgen_test_hamocc_omip_10days \
         --to-experiment checksuite.ocean_internal/hamocc/exp.test_hamocc_omip_10days \
	 --machines levante --without-configureflags '--enable-mixed' --list $listname
#-----------------------------------------------------------
#lets see the list
./lslist $listname
#-----------------------------------------------------------
