#!/bin/bash

addexp="./addexp"
#############################################################################
listname=debug1
./rmlist $listname

./create_all_builders $listname

./set_builder_flags Inactive --builders "$(./lslist $listname --builders-only)" --list $listname

./set_builder_flags Active --builders "levante_aurora levante_gcc_hybrid levante_gcc levante_intel_hybrid levante_intel DWD_nec_hybrid DWD_nec_yac2 DWD_nec" --list $listname

$addexp "checksuite.infrastructure/aurora/exp.icon_esm_r2b4.run" --builders "levante_aurora" --list $listname
$addexp "checksuite.infrastructure/aurora/exp.icon_atm_r2b4.run" --builders "levante_aurora" --list $listname

# DWD wave model test on levante
$addexp "checksuite.nwp/nwpexp.run_ICON_18_R2B4_waves"   --builders "levante_intel_hybrid"  --list $listname
$addexp "checksuite.nwp/nwpexp.run_ICON_19_R2B4_cmip_forcing"  --without-configureflags "--without-mpi" --runflags "cpu_time=00:30:00 no_of_nodes=1"  --machines levante --builders "levante_intel_hybrid levante_gcc_hybrid" --list $listname

$addexp exp.esm_bb_ruby0 --without-configureflags "--without-mpi" --builders "levante_gcc_hybrid levante_gcc levante_intel_hybrid levante_intel" --runflags "cpu_time=00:10:00 no_of_nodes=4" --list $listname
## Prototype-2:
$addexp exp.seamless_bb-proto2 --builders "levante_intel levante_gcc" --runflags "cpu_time=00:10:00 no_of_nodes=4" --list $listname
$addexp exp.seamless_bb-proto2 --builders "levante_intel_hybrid levante_gcc_hybrid" \
         --runflags "cpu_time=00:10:00 no_of_nodes=4 openmp_threads=4" --list $listname
## Prototype-1:
$addexp exp.seamless_bb-proto1 --builders "levante_intel levante_gcc levante_nag" --runflags "cpu_time=00:10:00 no_of_nodes=4" --list $listname
$addexp exp.seamless_bb-proto1 --builders "levante_intel_hybrid levante_gcc_hybrid" \
         --runflags "cpu_time=00:10:00 no_of_nodes=4 openmp_threads=4" --list $listname
## ICON-NWP/ECRAD test:
$addexp exp.seamless_bb-ecradmin --builders "levante_intel levante_gcc" --runflags "cpu_time=00:10:00 no_of_nodes=2" --list $listname
$addexp exp.seamless_bb-ecradmin --builders "levante_intel_hybrid levante_gcc_hybrid" \
         --runflags "cpu_time=00:10:00 no_of_nodes=2 openmp_threads=4" --list $listname
$addexp checksuite.nwp/nwpexp.run_ICON_19_R2B4_cmip_forcing                    --builders DWD_nec --list $listname

# DWD_nec_yac2
$addexp checksuite.nwp/nwpexp.run_ICON_17_R2B4_AO_coupled                      --builders DWD_nec_yac2 --list $listname
## Prototype 2
$addexp checksuite.nwp/nwpexp.run_ICON_20_R2B4_R2B6_AO_coupled                 --builders DWD_nec_yac2 --list $listname

$addexp checksuite.nwp/nwpexp.run_ICON_18_R2B4_waves   --builders DWD_nec_hybrid        --list $listname
$addexp checksuite.infrastructure/coupling/exp.run_ICON_17_R2B4_AO_coupled_LEVANTE.run --builders "levante_gcc levante_intel_hybrid" --list $listname
$addexp  checksuite.infrastructure/checkExternals/exp.check_externals_LEVANTE.run --builders "levante_gcc_hybrid levante_gcc levante_intel_hybrid levante_intel" --list ${listname}
$addexp test_nextGEMS.config --builders levante_intel_hybrid --list $listname
./lslist $listname
