#!/bin/bash

cd $(dirname "${BASH_SOURCE[0]}")

listname=tolerance
./rmlist $listname
./create_all_builders $listname

./list_part_tolerance $listname

# Tolerance references are only needed on CPU - turn off GPU builder
./set_builder_flags Inactive --builders 'DAINT_GPU_nvidia' --list $listname
./set_builder_flags Inactive --builders 'DAINT_GPU_nvidia_mixed' --list $listname

./lslist $listname
