#!/bin/bash

#############################################################################
##
## create build_only list
##
#############################################################################
listname=build_only
./rmlist $listname
./create_all_builders $listname
./set_builder_flags build_only --builders "$(./lslist $listname --builders-only)" --list $listname

./lslist $listname
#############################################################################
