#!/usr/bin/env python3

# This script adds the update experiments and post-processing scripts
# needed to generate update references to the list specified by `listname`.
# Note: This list must always be called as part of a full `create_list_<list>`,
#       it does not initialize any machines and builders.

import os
import sys

os.chdir(sys.path[0])

# get list name from argument
list=sys.argv[1]

testHandler  = {
  "exp.atm_qubicc_nc_test_update_base" : "checksuite.icon-dev/pp.refgen_atm_qubicc_nc_test_update-ref",
  "exp.aes_bubble_test_update_base" : "checksuite.icon-dev/pp.refgen_aes_bubble_test_update-ref",
}

for test, refgen in testHandler.items():
  # add qubicc_nc binary-identical test on DAINT and levante
  os.system(f"./addexp {test} --machines daint --list {list}")
  os.system(f"./addexp {test} --machines levante --list {list} --runflags='queue=compute'")

  os.system(f"./addexp {refgen} --machines 'daint levante' --list {list}")
  os.system(f"./adddep --from-experiment {refgen} --to-experiment {test} --machines 'daint levante' --list {list}")
