#! /usr/bin/env python3
# -*- coding: utf-8 -*-
#==============================================================================
# create an experiment list
#==============================================================================
from buildbot_config import BuildbotConfig
from icon_paths import buildbot_list_path

from pathlib import Path
import pickle
import click
import sys

@click.command()
@click.argument("name", type=str)
def lslist(name):

    full_list_name = buildbot_list_path / name

    if Path(full_list_name).exists():
      thisList = BuildbotConfig.from_pickle(full_list_name)
    else:
      print("did not find experiment list {}".format(full_list_name))
      sys.exit(1)

    print(thisList.to_string())

if __name__ == "__main__":
    lslist()
