#! /usr/bin/env python3
# -*- coding: utf-8 -*-
#==============================================================================
# delete an experiment lists
#==============================================================================
from buildbot_config import BuildbotConfig
from icon_paths import buildbot_list_path

from pathlib import Path
import pickle
import click
import sys

@click.command()
@click.argument("name", type=str)
def rmlist(name):

    full_list_name = buildbot_list_path / name

    if Path(full_list_name).exists():
        print("Experiment list "+name+" is deleted.")
        full_list_name.unlink()
    else:
        print("did not find experiment list {}. Doing nothing".format(full_list_name))


if __name__ == "__main__":
    rmlist()